### ISSUE TITLE
Use series instead of tags

### ISSUE THREAD

**Issue by dascritch** [dascritch/cpu-15#39]
http://plugins.dotaddict.org/dc2/details/series

**Comment by dascritch** [comment]
- [ ] install addon
- [ ] index posts
- [ ] copy templates to themes

**Comment by dascritch** [comment]
Discussion avec l'immense @franck-paul https://open-time.net/post/2016/12/28/Plugin-series-07-pour-Dotclear

**Comment by dascritch** [comment]
Pour la front page, si je veux reprendre l'image de la dernière émission pour chaque série, il faut que `<tpl:EntrySeries>` accepte une limite (lastn=1) .  Si c'est bien l'élément de template que j'imagine ;)

```
		<h2 class="notsobig">Séries d'émissions</h2>
		<tpl:Series limit="3">
			<tpl:EntrieSeries lastn="1">
				{{tpl:include src="_entry-serie.html"}}
			</tpl:EntrieSeries>		
		</tpl:Series>
```

**Comment by dascritch** [comment]
Bug étonnant sur la front-page <tpl:series limit="3"> ne me sort que 3 de mes séries, et loupe systématiquement "histoires de la cryptographie", quel que soit order=""

**Comment by dascritch** [comment]
Le bug de la widget "connexes" vient que la requête double quote les valeurs, et que notre config est sous PostGreSQL (les doubles quotes sont pour les noms de colonnes, il aurait fallut des simples quotes).
J'ai remonté l'info, peut-être au prochain déploiement ?

**Comment by dascritch** [comment]
Pour le front, pour ce que je veux (les dernières séries actives), il faut que je crée un élément de template car il faut ordonner par date de publication des billets
ça va faire une requête un peu brutale...

**Comment by franck-paul** [comment]
Pour le lien inactif sur le billet courant, le widget connexe le fait déjà (c'est une option) : 
Inclure le billet courant : Normal, Avec le lien, Aucun

**Comment by dascritch** [comment]
Oui mais ce widget ne marche ps en contexte postgres pour l'instant, et j'aimerais pouvoir étendre le langage de templates pour avoir plus de libertés.

**Comment by franck-paul** [comment]
Sinon je vais compléter un peu côté Dotclear pour les métadonnées (entre autres pour ajouter l'info de « fraîcheur » d'une série), ce qui permettra de trier ensuite dessus ;-)

**Comment by dascritch** [comment]
Pas mal !
À voir aussi si je peux trouver une astuce pour indiquer si les séries sont en cours ou complètes (telles “Bulletin de santé d´Internet 2017” pour CPU, ou encore les emoji pour mon blog).

**Comment by franck-paul** [comment]
https://hg.dotclear.org/dotclear/rev/ee69b09370ec
Ça sera dans la 2.14 de Dotclear (tri avant/arrière sur billet le plus récent/ancien)

Je sors dans la foulée une nouvelle version du plugin series qui utilisera cette possibilité avec la 2.14 (mais qui reste compatible avec la 2.13 et règle le problème du widget connexe)…

**Comment by dascritch** [comment]
\o/
je ferais quand même une balise spécifique pour ne pas répéter les billets par rapport aux 4 derniers sur la une

**Comment by franck-paul** [comment]
Ce qui revient, je pense, à demander les N dernières séries et ne pas afficher les 4 premières de la liste. À mon avis y'a moyen de faire ça juste avec les balises existantes (de la 2.14 s'entend) :-)

**Comment by dascritch** [comment]
Non, c'est plus subtil, puisque des billets peuvent ne pas être dans une série.
Y'a un repo quelque part sur ce plugin ? j'ai que le lien  vers le zip et ton billet dédié

**Comment by dascritch** [comment]
J'ai créé un `{{tpl::CountEntriesInSeries}}` pour avoir le nombre d'épisodes, mais les attributs `none="" one="" more=""` ne répondent pas :/
https://github.com/dascritch/cpu-15/blob/master/_public.php#L87

**Comment by franck-paul** [comment]
Non pas de repo (pour l'instant), enfin si mais privé.

Sinon pour vérifier le code généré tu peux toujours utiliser sysInfo (un plugin que j'ai développé). Ça permet de consulter le contenu du cache de template. En l'état c'est difficile à dire sans savoir quel(s) attribut(s) tu as utilisé.

**Comment by dascritch** [comment]
tu peux voir https://github.com/dascritch/cpu-15/blob/master/tpl/series.html#L27 rendu en https://cpu.dascritch.net/series

**Comment by dascritch** [comment]
Le widget "Connexes" marche bien. Mais je ne suis pas sûr de le garder, vu qu'on a un rappel en fin de billet.
BTW il manque des _behaviours_  dans les flux rss et atom pour ajouter les séries dans la liste des tags. Je l'ai fait manuellement de mon côté ;)
